### ISSUE TITLE
Consider using openjdk:8-jre-alpine as base image

### ISSUE THREAD

**Issue by J0WI** [crate/docker-crate#144]
The current image uses
https://github.com/crate/docker-crate/blob/fd4e206a6dedf45dd75066d359528f245781e4d5/Dockerfile#L7
https://github.com/crate/docker-crate/blob/fd4e206a6dedf45dd75066d359528f245781e4d5/Dockerfile#L13-L14

Have you considered using `openjdk:8-jre-alpine` or `openjdk:8-jre-alpine3.8`? This would trigger rebuilds on DockerHub if OpenJDK or depending libraries get patched.

**Comment by amotl** [comment]
Hi @J0WI,

thanks for writing in.

With #134, we moved away from Alpine and are using CentOS as a base image instead. While Alpine got some popularity with the advent of Docker because it was known to produce smaller images, the community experienced many flaws with it. The reason behind this is that is based on [musl](http://www.musl-libc.org/) instead of [glibc](https://www.gnu.org/software/libc/). While the former aims to be compatible with glibc, it is not quite the same and we saw others have been tripped by this fact as well - see [1,2,3] and many more.

So, I believe it will be safe to close this issue. Please let us know if you have any objections.

With kind regards,
Andreas.

[1] https://dev.to/asyazwan/moving-away-from-alpine-30n4
[2] https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26876
[3] https://monitoring-portal.org/t/strange-problem-with-2-8-2-under-alpine-linux/1979

cc @dhasilin, @Xplouder

**Comment by NinjaTycoon** [comment]
Good argument.  How about a minimal Ubuntu, then?  

As much as I love Centos for full blown servers, it is just very bloated for microservice scaling.  On top of that, with the confusing direction of Oracle with Centos 8, that leaves Centos 7 users in limbo.
