### ISSUE TITLE
No CE images available, literally 0 documentation for running on Docker

### ISSUE THREAD

**Issue by akamensky** [crate/docker-crate#193]
1. Current 4.4.3 image is enterprise build, not a CE one. No CE official images in sight.
2. There apparently used to be documentation for running on Docker, but not anymore (links from official image to docker specific docs are broken and redirect to "root" of documentation).

**Comment by amotl** [comment]
Dear Alexey,

thank you for writing in. I will try to answer your questions as concise and comprehensively as possible.

1. As far as I am aware of, we never published any CE builds so far in the past. However, beginning with version 4.5.0, there will be no discrimination between CE and EE variants anymore, all of CrateDB will fold into a single edition, see [1]. The release process is currently ongoing, and, until 4.5.0 will hit the official Docker release channel, you are welcome to use builds from the public Docker namespace we are maintaining on our own behalf, see [2].

2. A comprehensive guide for running CrateDB on Docker can be found at [3]. We are currently working on restructuring the documentation in order to improve discoverability.

Please let us know if you have further questions. Also, feel welcome to join us on our discussion forum at [4].

With kind regards,
Andreas.

[1] https://crate.io/press/entire-codebase-of-cratedb-open-source/
[2] `docker run -it --rm --publish 4200:4200 --publish 5432:5432 crate/crate:4.5.0`
[3] https://crate.io/docs/crate/howtos/en/latest/deployment/containers/docker.html
[4] https://community.crate.io/

**Comment by amotl** [comment]
Dear Alexey,

since you writing in, we've updated the documentation to improve discovery of the sections related to Docker. I will be closing this issue but also will be more than happy about listening to further suggestions from your end. So, feel free to reopen if you see fit.

With kind regards,
Andreas.
