### ISSUE TITLE
Raise default heap size?

### ISSUE THREAD

**Issue by robd003** [crate/docker-crate#208]
I noticed in the [Memory configuration](https://crate.io/docs/crate/howtos/en/latest/performance/memory.html#memory-configuration) section it says the heap should be set to 1GB minimum.

Should the 512mb limit be updated in the Docker files to reflect this?

**Comment by amotl** [comment]
@AishwaryaNaikare also reported about eventual issues with too less memory.

> I tried to solve it by the open source version, but I kept getting parsing and heap-related issues.

-- https://community.cratedb.com/chat/c/-/4/67

**Comment by seut** [comment]
@robd003 
Thanks for this suggestion and sorry for our very delayed answer.

We discussed this internally and disagreed to increase the docker default as the docker image is used in development setups with sometimes limited resources. E.g.:
 - We use it in our CI pipelines running on shared, or low-memory instances.
 - Some may use it for development, probably in addition to some application stack which requires memory.
 - ...

Most of these scenarios are working fine with the existing default of 512MB.
Instead of requiring more memory by default, we plan to adjust our documentation to highlight this fact and also encourage users to adjust it (e.g. by adding the `CRATE_HEAP_SIZE` usage to existing examples).


Compared to our tarball, which only sets the minimum HEAP to be used at the main java process to simplify development setups, this isn't possible with docker as with docker, the node will not run on the loopback interface. CrateDB treats loopback interface setups as development-only setups and will not run any bootstrap checks, thus allow such an non-optimized configuration.

**Comment by seut** [comment]
The documentation task is tracked by another issue, so I'm closing this.
