### ISSUE TITLE
image does not start

### ISSUE THREAD

**Issue by Marvin-TMG** [crate/docker-crate#209]
The image does not start, there is the following error:

```
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144] by adding `vm.max_map_count = 262144` to `/etc/sysctl.conf` or invoking `sysctl -w vm.max_map_count=262144`
```
Any ideas how to solve this?

I read that the following command can be ran before starting the image
`grep vm.max_map_count /etc/sysctl.conf vm.max_map_count=262144
`

**Comment by amotl** [comment]
Dear Marvin,

> `grep vm.max_map_count /etc/sysctl.conf vm.max_map_count=262144 `

This command would show you _if_ the corresponding setting is present in your `/etc/sysctl.conf` file.

On the other hand, the command `sysctl -w vm.max_map_count=262144` will invoke the setting ad hoc. In order to make it persistent / reboot-safe, you will have to add it to your `/etc/sysctl.conf` file.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

I hope you have been able to resolve the issue based on the information I shared with you. #203 just recently improved the documentation on this matter, about how to configure this system limit setting on the host system used within Docker Desktop. See [^1] for the full documentation section about _Configuring `vm.max_map_count`_.

Please reopen if you need more assistance on this topic.

With kind regards,
Andreas.

[^1]: https://github.com/crate/docker-crate/blob/master/tests/README.rst#configuring-vmmax_map_count
