### ISSUE TITLE
The latest docker image is out of date

### ISSUE THREAD

**Issue by reversefold** [crate/docker-crate#28]
When I docker pull crate:latest I'm getting 0.52.4. I'd expect at least 0.54.3 since that's the latest released version according to crate.io.

**Comment by reversefold** [comment]
It looks like the name of the image changed or an old name was deprecated. I was using crate:latest but if I switch to crate/crate:latest I get 0.54.3.

**Comment by mfussenegger** [comment]
Using `crate` instead of `crate/crate` is actually correct. 

`crate` is the official image that is also approved by docker.

`crate/crate` is **our** image, which might be a little edgier, since if we make changes to the docker images we try them there first.

The reason `crate` is still outdated is because the PR here https://github.com/docker-library/official-images/pull/1359 wasn't merged yet

**Comment by reversefold** [comment]
Ah, ok, thanks for the explanation.

--
Justin Patrin
Skyhigh Networks
Senior Scalability Engineer
