### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [crate/docker-crate#83]
I want to build this image on arm64 architecture, but I'm not sure that can be support arm64 architecture https://cdn.crate.io/downloads/releases/crate-2.1.5.tar.gz

**Comment by seut** [comment]
@longquan7 as crate uses java which is available for arm64 it should work fine.

**Comment by longquan7** [comment]
@seut OK, I will build this image on arm64 architecture.

**Comment by longquan7** [comment]
I want to konw this image if support can you add it to the https://hub.docker.com/u/arm64v8/ ?

**Comment by tianon** [comment]
Since this image is based on Alpine, multi-architecture support in official images will need to wait on gliderlabs/docker-alpine#304.

See https://github.com/docker-library/official-images#architectures-other-than-amd64 and https://github.com/docker-library/official-images#multiple-architectures for more information about multi-architecture official images. :+1:
